name: Generate Snake

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Runs daily at 00:00 Lagos time (23:00 UTC)
    - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      # Birthday Snake (December 19)
      - name: Generate Birthday Snake
        if: ${{ github.event.schedule && format('%m-%d', github.event.schedule) == '12-19' }}
        uses: Platane/snk@v3
        with:
          github_user_name: williamseben818-ux
          outputs: output/snake.svg
          snake_color: "#00FFFF,#FF00FF,#39FF14,#9400D3"
          background: "output/fireworks-bg.svg"
          speed: 5

      # Christmas Snake (December)
      - name: Generate Christmas Snake
        if: ${{ github.event.schedule && format('%m', github.event.schedule) == '12' }}
        uses: Platane/snk@v3
        with:
          github_user_name: williamseben818-ux
          outputs: output/snake.svg
          snake_color: "#FF0000,#008000,#FFD700"
          background: "output/christmas-bg.svg"
          speed: 4

      # Halloween Snake (October)
      - name: Generate Halloween Snake
        if: ${{ github.event.schedule && format('%m', github.event.schedule) == '10' }}
        uses: Platane/snk@v3
        with:
          github_user_name: williamseben818-ux
          outputs: output/snake.svg
          snake_color: "#FF8C00,#000000,#800080"
          background: "output/halloween-bg.svg"
          speed: 4

      # Default Snake (other months)
      - name: Generate Default Snake
        if: ${{ !(format('%m', github.event.schedule) == '12' || format('%m', github.event.schedule) == '10') }}
        uses: Platane/snk@v3
        with:
          github_user_name: williamseben818-ux
          outputs: output/snake.svg
          snake_color: "#1E90FF,#FFD700,#32CD32"
          background: "output/default-bg.svg"
          speed: 3

      - name: Commit and Push Snake SVG
        uses: EndBug/add-and-commit@v9
        with:
          add: 'output/snake.svg'
          message: 'Update seasonal snake animation'
